<?php

return array(
    'Instituições Gestoras, Deliberativas ou Consultivas de Cultura' => array(
        'Instituições Públicas' => array(
            'Conselho',
            'Comissão',
            'Empresa',
            'Frente',
            'Órgão Gestor'
        ),
        'Instituições Privadas' => array(
            'Conselho',
            'Comissão',
            'Empresa',
            'Fórum',
            'Órgão'
        ),
    ),
    'Empresas do Setor Cultural (CNAE)' => array(
        'Empresas de Fotografia' => array(
            'Estúdio fotográfico',
            'Laboratório fotográfico',
            'Fabricante de câmera fotográfica',
            'Fabricante de peças e acessórios fotográficos',
            'Comércio de produtos fotográficos',
        ),
        'Empresas de Design' => array(
            'Empresa de design'
        ),
        'Empresas de Moda' => array(
            'Organizadora/produtora de eventos',
            'Confecções têxteis',
            'Agência de modelos	'
        ),
        'Empresas de Arquitetura' => array(
            'Empresas de arquitetura'
        ),
        'Empresas de Artes Cênicas' => array(
            'Produtora de espetáculos',
            'Prestadora de serviços em cenografia',
            'Prestadora de serviços de som e iluminação para teatros',
            'Gestora de salas de teatros'
        ),
        'Empresas do Audiovisual' => array(
            'TV abertas',
            'TV por assinatura',
            'Programadora de TV por assinatura',
            'TV Universitária',
            'Emissora de Rádio',
            'Empresa de fabricação de película',
            'Empresa de locução',
            'Empresa de equipamentos de locação',
            'Produtora de conteúdo audiovisual',
            'Agência de notícias',
            'Fabricante de equipamentos de comunicação',
            'Fabricante de aparelhos de recepção, reprodução, gravação e amplificação de áudio e vídeo',
            'Fabricante de equipamentos e instrumentos ópticos, fotográficos e cinematográficos',
            'Fabricante de mídias virgens, magnéticas e ópticas',
            'Loja de equipamentos de áudio e vídeo',
            'Distribuidora cinematográfica, de vídeo e de programas de televisão',
            'Laboratório de filmes cinematográficos',
            'Laboratório para filmes de animação',
            'Prestadora de serviços de tv por assinatura',
            'Empresa de exibição cinematográfica',
        ),
        'Empresas do Mercado Editorial' => array(
            'Mídia Impressa',
            'Gráfica',
            'Editora',
            'Distribuidora',
            'Empresa de restauração',
            'Empresa de tradução'
        ),
        'Empresas da Música' => array(
            'Empresa de fabricação de instrumentos',
            'Empresa de restauração/reparação de instrumentos',
            'Comércio de instrumentos musicais',
            'Empresa de fabricação de CDs, DVDs',
            'Produtora',
            'Empresa montadora de Palco e Tenda',
            'Empresa de iluminação shows',
            'comércio de CDs, DVDs',
            'Empresa fabricante de amplificadores para instrumentos musicais',
            'Empresa fabricante de karaokê',
        ),
        'Empresas do Patrimônio Cultural' => array(
            'Empresa de Arquitetura e Restauração de Bens Edificados',
            'Empresa de Restauração de Bens Móveis',
            'Empresa de Arqueologia',
            'Empresa de Museologia',
            'Empresa de paisagismo',
            'Empresa de instrumentos e acessórios para bens do Patrimônio Imaterial',
            'Empresas de Pesquisa e Estudos voltados ao Patrimônio Cultural',
            'Comércio de carnaval',
        ),
        'Empresas da Cultura digital' => array(
            'Provedor de internet',
            'Empresa de criação de animação',
            'Empresa de criação de jogos eletrônicos',
            'Empresa de desenvolvimento e edição de software',
            'Empresa fabricante de aparelhos de videogame',
            'Agência de internet (para apreciação)',
        ),
        'Gestão Cultural' => array(
            'Empresa de consultoria e elaboração de projetos culturais'
        ),
        'Publicidade' => array(
            'Agência de publicidade'
        ),
    ),
    'Grupos de Cultura (Associações, Coletivos ou Cooperativas)' => array(
        'Grupos de Artes Visuais' => array(
            'Grupo de Arte Visual'
        ),
        'Grupos de Fotografia' => array(
            'Grupo de Fotografia'
        ),
        'Grupos de Design' => array(
            'Grupo de Design'
        ),
        'Grupos de Moda' => array(
            'Grupo de Moda'
        ),
        'Grupos de Arquitetura' => array(
            'Grupo de Arquitetura'
        ),
        'Grupos de Teatro' => array(
            'Grupo de Teatro'
        ),
        'Grupos de Circo' => array(
            'Grupo de Circo'
        ),
        'Grupos de Dança' => array(
            'Grupo de Dança'
        ),
        'Grupos de Audiovisual' => array(
            'Grupo de Audiovisual'
        ),
        'Grupos de Livro e leitura' => array(
            'Grupo de Livro e leitura'
        ),
        'Grupos de Música' => array(
            'Coral',
            'Orquestra',
            'Banda',
            'Conjunto musical',
            'Grupo de Livro e leitura'
        ),
        'Grupos Relacionados ao Patrimônio Cultural' => array(
            'Grupo Relacionado ao Patrimônio Cultural',
            'Grupo Parafolclórico',
            'Grupo de Capoeira',
            'Grupo Carnavalesco'
        ),
        'Grupos de Arte Digital' => array(
            'Grupos de Arte Digital'
        ),
        'Grupos de LGBT' => array(
            'Grupos de LGBT'
        ),
        'Agremiacoes de Carnaval' => array(
            'Escola de Samba',
            'Bloco de Carnaval'
        ),
        'Associações de Amigos' => array(
            'Associação de Amigos de Museus',
            'Associação de Amigos de centro cultural'
        ),
    ),
    'Povos, Comunidades ou Grupos Tradicionais' => array(
        'Povos Indígena' => array(
            'Povo Indígena ACONA (WAKONAS, NACONAS, JAKONA, ACORANES)',
            'Povo Indígena AIKANA (AIKANA, MASSAKA,TUBARAO)',
            'Povo Indígena AJURU',
            'Povo Indígena AKUNSU (AKUNT\'SU)',
            'Povo Indígena AMANAYE',
            'Povo Indígena AMONDAWA',
            'Povo Indígena ANAMBE',
            'Povo Indígena APARAI (APALAI)',
            'Povo Indígena APIAKA (APIACA)',
            'Povo Indígena APINAYE (APINAJE/APINAIE/APINAGE)',
            'Povo Indígena APURINA (APORINA, IPURINA, IPURINA, IPURINAN)',
            'Povo Indígena ARANA (ARACUAI DO VALE DO JEQUITINHONHA)',
            'Povo Indígena ARAPASO (ARAPACO)',
            'Povo Indígena ARARA DE RONDONIA (KARO, URUCU, URUKU)',
            'Povo Indígena ARARA DO ACRE (SHAWANAUA, AMAWAKA)',
            'Povo Indígena ARARA DO ARIPUANA (ARARA DO BEIRADAO/ARIPUANA)',
            'Povo Indígena ARARA DO PARA (UKARAGMA, UKARAMMA)',
            'Povo Indígena ARAWETE (ARAUETE)',
            'Povo Indígena ARIKAPU (ARICAPU, ARIKAPO, MASUBI, MAXUBI)',
            'Povo Indígena ARIKEM (ARIQUEN, ARIQUEME, ARIKEME)',
            'Povo Indígena ARIKOSE (ARICOBE)',
            'Povo Indígena ARUA',
            'Povo Indígena ARUAK (ARAWAK)',
            'Povo Indígena ASHANINKA (KAMPA)',
            'Povo Indígena ASURINI DO TOCANTINS (AKUAWA/AKWAWA)',
            'Povo Indígena ASURINI DO XINGU (AWAETE)',
            'Povo Indígena ATIKUM (ATICUM)',
            'Povo Indígena AVA-CANOEIRO',
            'Povo Indígena AWETI (AUETI/AUETO)',
            'Povo Indígena BAKAIRI (KURA, BACAIRI)',
            'Povo Indígena BANAWA YAFI (BANAWA, BANAWA-JAFI)',
            'Povo Indígena BANIWA (BANIUA, BANIVA, WALIMANAI, WAKUENAI)',
            'Povo Indígena BARA (WAIPINOMAKA)',
            'Povo Indígena BARASANA (HANERA)',
            'Povo Indígena BARE',
            'Povo Indígena BORORO (BOE)',
            'Povo Indígena BOTOCUDO (GEREN)',
            'Povo Indígena CANOE',
            'Povo Indígena CASSUPA',
            'Povo Indígena CHAMACOCO',
            'Povo Indígena CHIQUITANO (XIQUITANO)',
            'Povo Indígena CIKIYANA (SIKIANA)',
            'Povo Indígena CINTA LARGA (MATETAMAE)',
            'Povo Indígena COLUMBIARA (CORUMBIARA)',
            'Povo Indígena DENI',
            'Povo Indígena DESANA (DESANA, DESANO, DESSANO, WIRA, UMUKOMASA)',
            'Povo Indígena DIAHUI (JAHOI, JAHUI, DIARROI)',
            'Povo Indígena ENAWENE-NAWE (SALUMA)',
            'Povo Indígena FULNI-O',
            'Povo Indígena GALIBI (GALIBI DO OIAPOQUE, KARINHA)',
            'Povo Indígena GALIBI MARWORNO (GALIBI DO UACA, ARUA)',
            'Povo Indígena GAVIAO DE RONDONIA (DIGUT)',
            'Povo Indígena GAVIAO KRIKATEJE',
            'Povo Indígena GAVIAO PARKATEJE (PARKATEJE)',
            'Povo Indígena GAVIAO PUKOBIE (PUKOBIE, PYKOPJE, GAVIAO DO MARANHÃO)',
            'Povo Indígena GUAJA (AWA, AVA)',
            'Povo Indígena GUAJAJARA (TENETEHARA)',
            'Povo Indígena GUARANI KAIOWA (PAI TAVYTERA)',
            'Povo Indígena GUARANI M\'BYA',
            'Povo Indígena GUARANI NANDEVA (AVAKATUETE, CHIRIPA, NHANDEWA, AVA GUARANI)',
            'Povo Indígena GUATO',
            'Povo Indígena HIMARIMA (HIMERIMA)',
            'Povo Indígena INGARIKO (INGARICO, AKAWAIO, KAPON)',
            'Povo Indígena IRANXE (IRANTXE)',
            'Povo Indígena ISSE',
            'Povo Indígena JABOTI (JABUTI, KIPIU, YABYTI)',
            'Povo Indígena JAMAMADI (YAMAMADI, DJEOROMITXI)',
            'Povo Indígena JARAWA R A',
            'Povo Indígena JIRIPANCO (JERIPANCO, GERIPANCO)',
            'Povo Indígena JUMA (YUMA) Povo Indígena JURUNA',
            'Povo Indígena JURUTI (YURITI)',
            'Povo Indígena KAAPOR (URUBU-KAAPOR, KA\'APOR, KAAPORTE)',
            'Povo Indígena KADIWEU (CADUVEO, CADIUEU)',
            'Povo Indígena KAIABI (CAIABI, KAYABI)',
            'Povo Indígena KAIMBE (CAIMBE)',
            'Povo Indígena KAINGANG (CAINGANGUE)',
            'Povo Indígena KAIXANA (CAIXANA)',
            'Povo Indígena KALABASSA (CALABASSA, CALABACAS)',
            'Povo Indígena KALANCO',
            'Povo Indígena KALAPALO (CALAPALO)',
            'Povo Indígena KAMAYURA (CAMAIURA, KAMAIURA)',
            'Povo Indígena KAMBA (CAMBA)',
            'Povo Indígena KAMBEBA (CAMBEBA, OMAGUA)',
            'Povo Indígena KAMBIWA (CAMBIUA)',
            'Povo Indígena KAMBIWA PIPIPA (PIPIPA)',
            'Povo Indígena KAMPE',
            'Povo Indígena KANAMANTI (KANAMATI, CANAMANTI)',
            'Povo Indígena KANAMARI (CANAMARI, KANAMARY, TUKUNA)',
            'Povo Indígena KANELA APANIEKRA (CANELA)',
            'Povo Indígena KANELA RANKOKAMEKRA (CANELA)',
            'Povo Indígena KANINDE',
            'Povo Indígena KANOE (CANOE)',
            'Povo Indígena KANTARURE (CANTARURE)',
            'Povo Indígena KAPINAWA (CAPINAUA)',
            'Povo Indígena KARAJA (CARAJA)',
            'Povo Indígena KARAJA/JAVAE (JAVAE)',
            'Povo Indígena KARAJA/XAMBIOA (KARAJA DO NORTE)',
            'Povo Indígena KARAPANA (CARAPANA, MUTEAMASA, UKOPINOPONA)',
            'Povo Indígena KARAPOTO (CARAPOTO)',
            'Povo Indígena KARIPUNA (CARIPUNA)',
            'Povo Indígena KARIPUNA DO AMAPA (CARIPUNA)',
            'Povo Indígena KARIRI (CARIRI)',
            'Povo Indígena KARIRI-XOCO (CARIRI-CHOCO)',
            'Povo Indígena KARITIANA (CARITIANA)',
            'Povo Indígena KATAWIXI (KATAUIXI,KATAWIN, KATAWISI, CATAUICHI)',
            'Povo Indígena KATUENA (CATUENA, KATWENA)',
            'Povo Indígena KATUKINA (PEDA DJAPA)',
            'Povo Indígena KATUKINA DO ACRE',
            'Povo Indígena KAXARARI (CAXARARI)',
            'Povo Indígena KAXINAWA (HUNI-KUIN, CASHINAUA, CAXINAUA)',
            'Povo Indígena KAXIXO',
            'Povo Indígena KAXUYANA (CAXUIANA)',
            'Povo Indígena KAYAPO (CAIAPO)',
            'Povo Indígena KAYAPO KARARAO (KARARAO)',
            'Povo Indígena KAYAPO TXUKAHAMAE (TXUKAHAMAE)',
            'Povo Indígena KAYAPO XICRIM (XIKRIN)',
            'Povo Indígena KAYUISANA (CAIXANA, CAUIXANA, KAIXANA)',
            'Povo Indígena KINIKINAWA (GUAN, KOINUKOEN, KINIKINAO)',
            'Povo Indígena KIRIRI',
            'Povo Indígena KOCAMA (COCAMA, KOKAMA)',
            'Povo Indígena KOKUIREGATEJE',
            'Povo Indígena KORUBO',
            'Povo Indígena KRAHO (CRAO, KRAO)',
            'Povo Indígena KREJE (KRENYE)',
            'Povo Indígena KRENAK (BORUN, CRENAQUE)',
            'Povo Indígena KRIKATI (KRINKATI)',
            'Povo Indígena KUBEO (CUBEO, COBEWA, KUBEWA, PAMIWA, CUBEU)',
            'Povo Indígena KUIKURO (KUIKURU, CUICURO)',
            'Povo Indígena KUJUBIM (KUYUBI, CUJUBIM)',
            'Povo Indígena KULINA PANO (CULINA)',
            'Povo Indígena KULINA/MADIHA (CULINA, MADIJA, MADIHA)',
            'Povo Indígena KURIPAKO (CURIPACO, CURRIPACO, CORIPACO, WA KUENAI)',
            'Povo Indígena KURUAIA (CURUAIA)',
            'Povo Indígena KWAZA (COAIA, KOAIA)',
            'Povo Indígena MACHINERI (MANCHINERI, MANXINERI)',
            'Povo Indígena MACURAP (MAKURAP)',
            'Povo Indígena MAKU DOW (DOW)',
            'Povo Indígena MAKU HUPDA (HUPDA)',
            'Povo Indígena MAKU NADEB (NADEB)',
            'Povo Indígena MAKU YUHUPDE (YUHUPDE)',
            'Povo Indígena MAKUNA (MACUNA, YEBA-MASA)',
            'Povo Indígena MAKUXI (MACUXI, MACHUSI, PEMON)',
            'Povo Indígena MARIMAM (MARIMA)',
            'Povo Indígena MARUBO',
            'Povo Indígena MATIP U',
            'Povo Indígena MATIS',
            'Povo Indígena MATSE (MAYORUNA)',
            'Povo Indígena MAXAKALI (MAXACALI)',
            'Povo Indígena MAYA (MAYA)',
            'Povo Indígena MAYTAPU',
            'Povo Indígena MEHINAKO (MEINAKU, MEINACU)',
            'Povo Indígena MEKEN (MEQUEM, MEKHEM, MICHENS)',
            'Povo Indígena MENKY (MYKY, MUNKU, MENKI, MYNKY)',
            'Povo Indígena MIRANHA (MIRANHA, MIRANA)',
            'Povo Indígena MIRITI TAPUIA (MIRITI-TAPUYA, BUIA-TAPUYA)',
            'Povo Indígena MUNDURUKU (MUNDURUCU)',
            'Povo Indígena MURA',
            'Povo Indígena NAHUKWA (NAFUQUA)',
            'Povo Indígena NAMBIKWARA DO CAMPO (HALOTESU, KITHAULU,WAKALITESU, SAWENTES, MANDUKA)',
            'Povo Indígena NAMBIKWARA DO NORTE (NEGAROTE, MAMAINDE, LATUNDE, SABANE E MANDUKA, TAWANDE)',
            'Povo Indígena NAMBIKWARA DO SUL (WASUSU, HAHAINTESU,ALANTESU, WAIKISU, ALAKETESU, WASUSU, SARARE)',
            'Povo Indígena NARAVUTE (NARUVOTO)',
            'Povo Indígena NAWA (NAUA)',
            'Povo Indígena NUKINI (NUQUINI, NUKUINI)',
            'Povo Indígena OFAIE (OFAYE-XAVANTE)',
            'Povo Indígena ORO WIN',
            'Povo Indígena PAIAKU (JENIPAPO-KANINDE)',
            'Povo Indígena PAKAA NOVA (WARI, PACAAS NOVOS)',
            'Povo Indígena PALIKUR (AUKWAYENE, AUKUYENE, PALIKU\'ENE)',
            'Povo Indígena PANARA (KRENHAKARORE, KRENAKORE, KRENAKARORE)',
            'Povo Indígena PANKARARE (PANCARARE)',
            'Povo Indígena PANKARARU (PANCARARU)',
            'Povo Indígena PANKARARU KALANKO (KALANKO)',
            'Povo Indígena PANKARARU KARUAZU (KARUAZU)',
            'Povo Indígena PANKARU (PANCARU)',
            'Povo Indígena PARAKANA (PARACANA, APITEREWA, AWAETE)',
            'Povo Indígena PARECI (PARESI, HALITI)',
            'Povo Indígena PARINTINTIN',
            'Povo Indígena PATAMONA (KAPON)',
            'Povo Indígena PATAXO',
            'Povo Indígena PATAXO HA-HA-HAE',
            'Povo Indígena PAUMARI (PALMARI)',
            'Povo Indígena PAUMELENHO',
            'Povo Indígena PIRAHA (MURA PIRAHA)',
            'Povo Indígena PIRATUAPUIA (PIRATAPUYA, PIRATAPUYO, PIRATAPUYA, WAIKANA)',
            'Povo Indígena PITAGUARI',
            'Povo Indígena POTIGUARA',
            'Povo Indígena POYANAWA (POIANAUA)',
            'Povo Indígena RIKBAKTSA (CANOEIROS, ERIGPAKTSA)',
            'Povo Indígena SAKURABIAT (MEKENS, SAKIRABIAP, SAKIRABIAR)',
            'Povo Indígena SATERE-MAWE (SATERE-MAUE)',
            'Povo Indígena SHANENAWA (KATUKINA)',
            'Povo Indígena SIRIANO (SIRIA-MASA)',
            'Povo Indígena SURIANA',
            'Povo Indígena SURUI DE RONDONIA (PAITER)',
            'Povo Indígena SURUI DO PARA (AIKEWARA)',
            'Povo Indígena SUYA (SUIA/KISEDJE)',
            'Povo Indígena TAPAYUNA (BEICO-DE-PAU)',
            'Povo Indígena TAPEBA',
            'Povo Indígena TAPIRAPE (TAPI\'IRAPE)',
            'Povo Indígena TAPUIA (TAPUIA-XAVANTE, TAPUIO)',
            'Povo Indígena TARIANO (TARIANA, TALIASERI)',
            'Povo Indígena TAUREPANG (TAULIPANG, PEMON, AREKUNA, PAGEYN)',
            'Povo Indígena TEMBE',
            'Povo Indígena TENHARIM',
            'Povo Indígena TERENA',
            'Povo Indígena TICUNA (TIKUNA, TUKUNA, MAGUTA)',
            'Povo Indígena TINGUI BOTO',
            'Povo Indígena TIRIYO EWARHUYANA (TIRIYO, TRIO, TARONA, YAWI, PIANOKOTO)',
            'Povo Indígena TIRIYO KAH\'YANA (TIRIYO, TRIO, TARONA, YAWI, PIANOKOTO)',
            'Povo Indígena TIRIYO TSIKUYANA (TIRIYO, TRIO, TARONA, YAWI, PIANOKOTO)',
            'Povo Indígena TORA',
            'Povo Indígena TREMEMBE',
            'Povo Indígena TRUKA',
            'Povo Indígena TRUMAI',
            'Povo Indígena TSOHOM DJAPA (TSUNHUM-DJAPA)',
            'Povo Indígena TUKANO (TUCANO, YE\'PA-MASA, DASEA)',
            'Povo Indígena TUMBALALA',
            'Povo Indígena TUNAYAN A',
            'Povo Indígena TUPARI',
            'Povo Indígena TUPINAMBA',
            'Povo Indígena TUPINIQUIM',
            'Povo Indígena TURIWARA',
            'Povo Indígena TUXA',
            'Povo Indígena TUYUKA (TUIUCA, DOKAPUARA, UTAPINOMAKAPHONA)',
            'Povo Indígena TXIKAO (TXICAO, IKPENG)',
            'Povo Indígena UMUTINA (OMOTINA, BARBADOS)',
            'Povo Indígena URU-EU-WAU-WAU (URUEU-UAU-UAU, URUPAIN, URUPA)',
            'Povo Indígena WAI WAI HIXKARYANA (HIXKARYANA)',
            'Povo Indígena WAI WAI KARAFAWYANA (KARAFAWYANA, KARAPAWYANA)',
            'Povo Indígena WAI WAI XEREU (XEREU)',
            'Povo Indígena WAI WAI KATUENA (KATUENA)',
            'Povo Indígena WAI WAI MAWAYANA (MAWAYANA)',
            'Povo Indígena WAIAPI (WAYAMPI, OYAMPI, WAYAPY)',
            'Povo Indígena WAIMIRI ATROARI (KINA)',
            'Povo Indígena WANANO (UANANO, WANANA)',
            'Povo Indígena WAPIXANA (UAPIXANA, VAPIDIANA, WAPISIANA,WAPISHANA)',
            'Povo Indígena WAREKENA (UAREQUENA, WEREKENA)',
            'Povo Indígena WASSU',
            'Povo Indígena WAURA (UAURA, WAUJA)',
            'Povo Indígena WAYANA (WAIANA, UAIANA)',
            'Povo Indígena WITOTO (UITOTO, HUITOTO)',
            'Povo Indígena XAKRIABA (XACRIABA)',
            'Povo Indígena XAVANTE (A\'UWE, AKWE, AWEN, AKWEN)',
            'Povo Indígena XERENTE (AKWE, AWEN, AKWEN)',
            'Povo Indígena XETA',
            'Povo Indígena XIPAIA (SHIPAYA, XIPAYA)',
            'Povo Indígena XOKLENG (SHOKLENG, XOCLENG)',
            'Povo Indígena XOKO (XOCO, CHOCO)',
            'Povo Indígena XUKURU (XUCURU)',
            'Povo Indígena XUKURU KARIRI (XUCURU-KARIRI)',
            'Povo Indígena YAIPIYANA',
            'Povo Indígena YAMINAWA (JAMINAWA, IAMINAWA)',
            'Povo Indígena YANOMAMI NINAM (IANOMAMI, IANOAMA, XIRIANA)',
            'Povo Indígena YANOMAMI SANUMA (IANOMAMI, IANOAMA, XIRIANA)',
            'Povo Indígena YANOMAMI YANOMAM (IANOMAMI, IANOAMA, XIRIANA)',
            'Povo Indígena YAWALAPITI (IAUALAPITI)',
            'Povo Indígena YAWANAWA (IAUANAUA)',
            'Povo Indígena YEKUANA (MAIONGON, YE\'KUANA, YEKWANA, MAYONGONG)',
            'Povo Indígena YUDJA (JURUNA, YURUNA)',
            'Povo Indígena ZO\'E (POTURU)',
            'Povo Indígena ZORO (PAGEYN)',
            'Povo Indígena ZURUAHA (SOROWAHA, SURUWAHA)',
        ),
        'Povos e Comunidades Tradicionais' => array(
            'Comunidade quilombola',
            'Povo cigano',
            'Comunidor de pescadores',
            'Povo de terreiro',
            'Comunidadade ribeirinho',
            'irmandade de negros',
            'Comunidade agricultor tradicional',
            'Comunidade caiçara',
            'Comunidade faxinal',
            'Comunidade de pomeranos',
            'Comunidade pantaneira',
            'Comudade quebradeira de coco-de-babaçu',
            'Comunidade marisqueira',
            'Comunidade caranguejeira',
            'Comunidade agroextrativista',
            'Comunidade seringueiro',
            'Comunidade sertaneja',
            'Comunidade geraizeiro',
            'Comunidade de fundo de pasto',
            'Comunidade açoriana',
            'Comunidade caatingueira',
            'Comunidade de campeiro',
            'Comunidade de jangadeiro',
        ),
        'Comunidades de culturas estrangeiras' => array(
            'Em apreciação'
        ),
    ),
    'Patrocinadores, Financiadores e Incentivadores Culturais' => array(
        'Patrocinadores, Financiadores e Incentivadores Culturais - Pessoa Física' => array(
            'Patrocinador, Financiador e Incentivador Cultural - Pessoa Física'
        ),
        'Patrocinadores, Financiadores e Incentivadores Culturais - Pessoa Jurídica de natureza privada' => array(
            'Empresa Privada com fins lucrativos (Exceto Instituições Financeiras)',
            'Empresa Pública (Exceto Instituições Financeiras)',
            'Empresa Privada sem fins lucrativos (OS, OSCIPS, Associações, Entidades de Classe, Cooperativas)',
            'Empresa de Economia Mista',
            'Instituições Financeiras',
        ),
        'Patrocinadores, Financiadores e Incentivadores Culturais - Pessoa Jurídica de natureza Pública' => array(
            'Entidade ou Fundo Público Federal',
            'Entidade ou Fundo Público Distrital',
            'Entidade ou Fundo Público Estadual',
            'Entidade ou Fundo Público Municipal',
        ),
        'Organizações Internacionais' => array(
            'Organização Internacional Multilateral',
            'Organização Internacional Regional'
        ),
        'Governos Estrangeiros' => array(
            'Governo Estrangeiro - Embaixada',
            'Governo Estrangeiro - Consulado',
            'Governo Estrangeiro - Escritório de Representação',
            'Governo Estrangeiro - Entidade de Promoção Cultural'
        ),
    ),
    'Demais Agentes Culturais' => array(
        'Mestres de Cultura' => array(
            'Mestre de Saberes Tradicionais (incluídos os Mestres de Cultura Popular)',
            'Mestre de Cultura de Outros Saberes',
            'Agentes de leitura'
        )
    )
);
